[package]
name = "game"
version = "0.1.0"
authors = ["Luke Jones <luke@ljones.dev>"]
edition = "2018"
license = "MPL-2.0"

[[bin]]
name = "diirdoom"
path = "src/main.rs"

[dependencies]
vec2d = { path = "../vec2d" }
glam = "0.8.5"
gumdrop = "~0.7"
rand = "*"
wad = { path = "../wad" }

[dependencies.sdl2]
version = "0.32"
default-features = false
features = ["gfx"]

[dev-dependencies]
gumdrop = "~0.7"
wad = { path = "../wad" }
