[package]
name = "wad"
version = "0.1.0"
authors = ["Luke Jones <luke@ljones.dev>"]
edition = "2018"
license = "MPL-2.0"
license-file = "../LICENSE"


[dependencies]

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmarks"
harness = false
path = "benches/bench.rs"
