image: rustdocker/rust:stable

stages:
    - test
    - rustfmt
    - clippy
    - deploy

test:
  script:
    - cargo check --verbose --all
    - cargo test --verbose --all
rustfmt:
  script:
    - rustup component add rustfmt
    - cargo fmt --all -- --check
clippy:
  script:
    - rustup component add clippy
    - cargo clippy --all

pages:
  image: rustdocker/rust:stable
  stage: deploy
  only:
    - master
  script:
    - cargo doc --no-deps
    - rm -rf public
    - mkdir public
    - cp -R target/doc/* public
    - cp misc/index.html public
  artifacts:
    paths:
    - public
