max_width =80
comment_width = 80
wrap_comments = false

brace_style = "PreferSameLine"

reorder_imports = true

enum_discrim_align_threshold = 30
struct_field_align_threshold = 30
fn_single_line = true