[package]
name = "utils"
version = "0.1.0"
authors = ["Luke Jones <luke@ljones.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.8.5"